### ISSUE TITLE
Vault Gaming Logo

### ISSUE THREAD

**Issue by XavierJohnson** [Hual/samp-discord-plugin#10]
Vault Gaming Logo
![samp2](https://user-images.githubusercontent.com/34948045/37203050-466a252c-2341-11e8-957d-01b96b6f102c.jpg)

IP:94.23.208.199:9877

**Comment by BigETI** [comment]
Is this a RW:MP server?

**Comment by XavierJohnson** [comment]
@BigETI Of course not.
This is SA:MP.

**Comment by BigETI** [comment]
![No](https://cdn.discordapp.com/attachments/231799180127895553/421617420923568128/unknown.png)

![Yes](https://cdn.discordapp.com/attachments/231799180127895553/421617443958685696/unknown.png)

???

**Comment by XavierJohnson** [comment]
This was on RWMP forums.
