### ISSUE TITLE
Le Monde RolePlay

### ISSUE THREAD

**Issue by LaMoulaga** [Hual/samp-discord-plugin#104]
Hello !
Server IP : SERVEUR.LM-RP.FR:2600 or 213.32.83.152:2600

Server Name : Le Monde Roleplay

https://i.imgur.com/Kgp6wZB.png
![LeMondeRoleplay](https://user-images.githubusercontent.com/69083467/89104619-ea198280-d41a-11ea-802d-0e746930b1ad.png)

Thanks !

**Comment by AmyrAhmady** [comment]
Done
