### ISSUE TITLE
Server Logo Petition > GTA Multigames

### ISSUE THREAD

**Issue by lncell** [Hual/samp-discord-plugin#105]
Hi there, please add this server :)
Address: play.gtamultigames.com:7777 or 192.99.251.110:7777

![Logo](https://user-images.githubusercontent.com/69117994/89128143-1daaea00-d4b9-11ea-8f39-9bce32d0f903.jpg)

Thanks for your attention!

**Comment by AmyrAhmady** [comment]
Done
