### ISSUE TITLE
Server Logo | Brasil Vida Real RPG

### ISSUE THREAD

**Issue by yBrunno** [Hual/samp-discord-plugin#108]
Server ip > jogar.brasilvidareal.com:7777
Logo > [https://imgur.com/a/8J2f0IO](url)
![Logo BvR](https://user-images.githubusercontent.com/69360933/89669700-4d416400-d8b6-11ea-8bef-e4503c3a73e4.png)

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, post a comment here or open a new issue.
