### ISSUE TITLE
Diamond Roleplay Br

### ISSUE THREAD

**Issue by kkUriel** [Hual/samp-discord-plugin#109]
Nome do servidor: Diamond Roleplay Br
Endereço IP: 198.50.217.188:7777
Logo: 
https://cdn.discordapp.com/icons/705413550641774703/5eddbf7aea07e06ca7d793cc552a3174.png?size=2048

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, post a comment here or open a new issue.
