### ISSUE TITLE
Vice Roleplay | New IP address update 

### ISSUE THREAD

**Issue by wildcl4WZ** [Hual/samp-discord-plugin#113]
Hostname: Vice Roleplay | Zeppelin
IP: 149.202.65.6:7777

https://www.upload.ee/image/12336414/vicem.png

**New IP address**
Update request

Past issues: https://github.com/Hual/samp-discord-plugin/issues/77

**Comment by wildcl4WZ** [comment]
@Hual @BigETI just always love

**Comment by AmyrAhmady** [comment]
@wildcl4WZ You link is not valid anymore, please upload it in a proper website like imgur or just upload it here, you can drag and drop your pictures here and post them

**Comment by wildcl4WZ** [comment]
![512](https://user-images.githubusercontent.com/42044566/122766286-067c1300-d2aa-11eb-882d-65bcc4bb3adf.png)
@AmyrAhmady

**Comment by AmyrAhmady** [comment]
@wildcl4WZ Done, sorry for late response.
