### ISSUE TITLE
Venezuela RolePlay - Server Logo

### ISSUE THREAD

**Issue by kaizerpwn** [Hual/samp-discord-plugin#118]
HostName: [VZ] Venezuela RP >> DISCORD : discord.gg/BHUVGj
Address:  193.70.65.226:7841

Logo request : 
https://i.postimg.cc/C1TNPTwj/venezuelalogo.png

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, post a comment here or open a new issue.
