### ISSUE TITLE
CMLV-RP

### ISSUE THREAD

**Issue by MSk0r** [Hual/samp-discord-plugin#120]
https://i.imgur.com/6pE4fKi.png

HostName: [FR]CMLV 0.3.dl MAJ 10.6.5 - l'Aventure continue
Address:  server.cmlv-rp.com:2600
Players:  4 / 400
Ping:     626
Mode:     CMLV v10.6.5 RP
Language: Français

Thanks (:

**Comment by AmyrAhmady** [comment]
Done
