### ISSUE TITLE
LeRoleplay.FR

### ISSUE THREAD

**Issue by MSk0r** [Hual/samp-discord-plugin#121]
https://i.imgur.com/d4NoVB2.png

If this logo is not supported, please use this one: https://i.imgur.com/RKvcF7g.png

HostName: (FR) LEROLEPLAY.FR - Be All You Can't Be
Address:  149.202.64.55:1200
Players:  69 / 600
Ping:     29
Mode:     LRP V3.2 DL
Language: FR

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, post a comment here or open a new issue.
