### ISSUE TITLE
Country Roleplay

### ISSUE THREAD

**Issue by SetNabilObject** [Hual/samp-discord-plugin#122]
Hostname : Country Roleplay
IP : 20.184.5.0:7777
Gamemode : C-RP | V1.0
Language : Indonesia

Thanks :)

Image : 
![20201105_104226](https://user-images.githubusercontent.com/71818199/98195368-2ac1f400-1f54-11eb-8046-747ab0630714.jpg)

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, post a comment here or open a new issue.
