### ISSUE TITLE
PrideCity Roleplay

### ISSUE THREAD

**Issue by MZZaky27** [Hual/samp-discord-plugin#123]
HostName: PrideCity Roleplay [0.3DL]
Address:  103.55.38.93:7777
Mode:     PC:RP V1.0
Language: Indonesia

Image:
![o](https://user-images.githubusercontent.com/74539054/99243194-e7f4fb80-2832-11eb-914b-4fc29bda349d.png)

Thanks

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, post a comment here or open a new issue.
