### ISSUE TITLE
los santos role  play(.net)

### ISSUE THREAD

**Issue by Jarek606** [Hual/samp-discord-plugin#124]
HostName: Los Santos RolePlay | ls-rp.net
Address:  gra.ls-rp.net:7777
149.202.198.161:7777
Language: Polish
![logo-512x512](https://user-images.githubusercontent.com/3933815/99881490-67f7d880-2c1a-11eb-93d8-68c445fc6bd4.png)

**Comment by AmyrAhmady** [comment]
Done (your IP is invalid, so I linked your picture to your hostname)
