### ISSUE TITLE
Brasil Game Show RPG

### ISSUE THREAD

**Issue by Real-DavidWilson** [Hual/samp-discord-plugin#125]
HostName: Brasil Game Show
Address: 192.99.185.72:7777
Mode: RPG
Language: Português | Brasil
![bgs logo](https://user-images.githubusercontent.com/68564443/100109330-7e847680-2e4a-11eb-8d2a-9cf321dfe45c.jpg)
Obrigado.

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, post a comment here or open a new issue.
