### ISSUE TITLE
City of Manila Roleplay

### ISSUE THREAD

**Issue by eksqtr** [Hual/samp-discord-plugin#128]
![51 79 161 204](https://user-images.githubusercontent.com/43538516/101268631-74df0500-37a0-11eb-8ff0-a5d47c5c36d8.png)
![samp equitygaming net](https://user-images.githubusercontent.com/43538516/101268638-83c5b780-37a0-11eb-8f86-55f8b689feb4.png)

**Comment by AmyrAhmady** [comment]
You are not providing your server IP, please read the requirements and open a **new issue** if your server is still available.
