### ISSUE TITLE
Indonesia RolePlay | SAMP VOICE

### ISSUE THREAD

**Issue by fachridantm** [Hual/samp-discord-plugin#132]
Hostname : Indonesia RolePlay | Promosi X2
IP : 51.79.210.69:7777

https://i.postimg.cc/ZqLfwgSm/samp-logo-png-6.png

Thanks:)

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, please consider opening a **new issue**.
