### ISSUE TITLE
Custom Logo Request - GTAPinas

### ISSUE THREAD

**Issue by janpul** [Hual/samp-discord-plugin#134]
Hi! I would like to request to put up our logo in the samp-discord-plugin of yours.

IP: 51.79.167.244:7777
IMAGE: https://gtapinas.com/wp-content/uploads/2020/09/rsz_gta-1.png

Thank you and have a great day!

![image](https://user-images.githubusercontent.com/76933383/103504678-1edea980-4e93-11eb-9d6f-c3fa73bcdb6c.png)

**Comment by AmyrAhmady** [comment]
Done
