### ISSUE TITLE
Cidade do Brasil RPS

### ISSUE THREAD

**Issue by VITORARAGAO** [Hual/samp-discord-plugin#136]
HostName: Cidade do Brasil
Address: 192.99.136.1:7797
Mode: RPS
Language: Português | Brasil

![LOGO2 CB 512x512](https://user-images.githubusercontent.com/42947492/104122402-91cca200-5323-11eb-8cda-a93f7efbff13.png)

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, please consider opening a **new issue**.
