### ISSUE TITLE
Vanquisher Roleplay - Custom Logo Request

### ISSUE THREAD

**Issue by wolfyydz** [Hual/samp-discord-plugin#138]
Greetings to the github discord plugin moderator(s),

I would like to request a discord rich presence custom logo in our server using your samp discord plugin, thank you and have a good day.

Server IP Address: 139.99.42.196:7777
Logo:
![Logo](https://user-images.githubusercontent.com/77426919/104545930-142bcd80-5666-11eb-8ccb-83a4fd1c8d52.jpg)

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, please consider opening a **new issue**.
