### ISSUE TITLE
Leroleplay.fr

### ISSUE THREAD

**Issue by mrjustin24** [Hual/samp-discord-plugin#139]
Greetings to the github discord plugin moderator(s),

I would like to request a discord rich presence custom logo in our server using your samp discord plugin, thank you and have a good day.

It's the real logo because someone gave a random image.
Server IP Address: 149.202.64.55:1200
Logo (512x512):
https://www.zupimages.net/up/21/04/o7bh.png

**Comment by mrjustin24** [comment]
@Hual

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, please consider opening a **new issue**.
