### ISSUE TITLE
Process deadlock on /q

### ISSUE THREAD

**Issue by VictorFerraresi** [Hual/samp-discord-plugin#14]
Seems like the plugin is generating some kind of DeadLock in the Discord::Shutdown() call @ the unhook, that makes the GTA SA freeze when you /q. You're forced to quit the game via CTRL+ALT+DEL.

**Comment by Hual** [comment]
Is there any specific way to reproduce it?

**Comment by VictorFerraresi** [comment]
I don't know if I've done something wrong, but simply by loading it via modloader I can't /q at all. My screen freezes, the SAMP mouse keeps moving if I want, and I have to CTRL ALT DEL to delete the gta_sa.exe. 100% of the times, no specific thing to be done to reproduce. It doesn't happens only for me.

**Comment by Hual** [comment]
I haven't tested using modloader, just a generic ASI loader.

**Comment by VictorFerraresi** [comment]
I've just tried it with the Silent ASI's loader, dropping the .asi on the root folder of the GTA_SA.exe. Same behaviour

**Comment by Hual** [comment]
And you can reproduce it every time? If so, what OS are you running?

**Comment by VictorFerraresi** [comment]
100% of the times. Windows 7 64b 7601 compilation with SP1. Seems like someone else already faced this problem and posted it on the last page of your SAMP Forum's topic of this tool.

**Comment by VictorFerraresi** [comment]
Seems like my W10 users(players) are not facing this issue, only the W7 ones.

**Comment by Hual** [comment]
Can you try the new build?

**Comment by VictorFerraresi** [comment]
Still the same behaviour. 100% of my server's W10 users have no issue with the /q at all.

**Comment by VictorFerraresi** [comment]
https://blogs.msdn.microsoft.com/oldnewthing/20040127-00/?p=40873/ I'm risking to say it's something about this

**Comment by Hual** [comment]
Resolved in 85bb34beb6961dc325c7f78e89d7f9596f6b1624.
