### ISSUE TITLE
Logo Request

### ISSUE THREAD

**Issue by PateeerQ** [Hual/samp-discord-plugin#140]
IP: samp.lunarpride.xyz:7777

THANK YOU SO MUCH

Logo:
![image](https://user-images.githubusercontent.com/72560259/107194119-3b39ad00-6a22-11eb-910e-9c397690888f.png)

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, please consider opening a **new issue**.
