### ISSUE TITLE
Los Santos Stories - Roleplay LOGO

### ISSUE THREAD

**Issue by errkedukke** [Hual/samp-discord-plugin#141]
Hello I would like you to add our logo to our IP address which is: 80.241.245.126:1113

![logo](https://user-images.githubusercontent.com/38571128/107220157-77254000-6a2b-11eb-9c0a-b4ee6d9b4631.png)

**Comment by errkedukke** [comment]
Hey @Hual !

Any news on it?

**Comment by AmyrAhmady** [comment]
Done
