### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by OndiOnai** [Hual/samp-discord-plugin#143]
Kumarikandam Roleplay
IP: 139.180.141.201:1989
I don't want IP to be displayed

![20210126_181902](https://user-images.githubusercontent.com/78967554/107780647-f6d54680-6d6c-11eb-9e9b-a31ef1bca147.png)

**Comment by AmyrAhmady** [comment]
It is not possible to hide server ip for a specific server only at the moment. Please create an issue again if you want me to add your logo anyway
