### ISSUE TITLE
logo discord request

### ISSUE THREAD

**Issue by ServidorPara** [Hual/samp-discord-plugin#150]
https://www.xmple.com/wallpaper/yellow-black-honeycomb-hexagon-beehive-512x512-c2-000000-ffd700-l2-5-79-a-25-f-5.svg

Ip server: 93.114.82.235:7777

Thanks

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, please consider opening a **new issue**.
