### ISSUE TITLE
Los Santos Stories - new logo

### ISSUE THREAD

**Issue by errkedukke** [Hual/samp-discord-plugin#154]
Like you ever added an old one but sure let's go for it.
PLS add this logo: 
https://media.discordapp.net/attachments/808012090136592414/833700310018031616/lss-logo.png?width=522&height=373
IP: 80.241.245.126:1113

**Comment by AmyrAhmady** [comment]
@errkedukke your image must be 512x512 or higher, and it needs to be squared, please fix that and I will add it to the list

**Comment by errkedukke** [comment]
@AmyrAhmady 

Hey, you can use this picture, thank you! 
https://user-images.githubusercontent.com/38571128/107220157-77254000-6a2b-11eb-9c0a-b4ee6d9b4631.png

**Comment by AmyrAhmady** [comment]
Done.
