### ISSUE TITLE
San Andreas Global: SA-MP (Server 'Light Roleplay')

### ISSUE THREAD

**Issue by JonHien** [Hual/samp-discord-plugin#159]
Hi Hual, Hope you read this from me soon.

Server Name: **San Andreas Global: SA-MP**
IP Address: **SAG-MP.COM:7777**
Logo Server: **https://i.imgur.com/BpfeY66.png**
[img]https://i.imgur.com/BpfeY66.png[/img]

**Comment by JonHien** [comment]
@Hual

**Comment by Heaaven** [comment]
https://sampdiscord.fr

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, please consider opening a **new issue**.
