### ISSUE TITLE
Relentless Gaming Freeroam/Roleplay

### ISSUE THREAD

**Issue by LordGame1** [Hual/samp-discord-plugin#160]
IP: 89.40.4.118:7777
logo:  https://i.imgur.com/w0Fq4oS.png

**Comment by Heaaven** [comment]
https://sampdiscord.fr

**Comment by AmyrAhmady** [comment]
@LordGame1 Your logo must be 512x512 or higher, and squared, please read https://github.com/Hual/samp-discord-plugin#how-to-add-your-own-servers-with-custom-logos
