### ISSUE TITLE
WTLS - Welcome to Los Santos

### ISSUE THREAD

**Issue by Helomyname171** [Hual/samp-discord-plugin#162]
The IP for this community will be divided into four different servers.

Server 1: s1.gta-multiplayer.cz:7777
Server 2: s2.gta-multiplayer.cz:7777
Server 3: s3.gta-multiplayer.cz:7777
Server 4: s4.gta-multiplayer.cz:7777
Logo: https://imgur.com/a/iCipZMC

**Comment by Heaaven** [comment]
https://sampdiscord.fr

**Comment by AmyrAhmady** [comment]
Done
