### ISSUE TITLE
ShaX Hirsiz Polis 80.93.220.82:7777

### ISSUE THREAD

**Issue by Shacous** [Hual/samp-discord-plugin#163]
![shaxsky](https://user-images.githubusercontent.com/83518870/120896889-3b426600-c62c-11eb-82e1-d433af3fc820.png)
80.93.220.82:7777

**Comment by Heaaven** [comment]
https://sampdiscord.fr

**Comment by AmyrAhmady** [comment]
Duplicate of #156 , it has been added already.
