### ISSUE TITLE
https://sampdiscord.fr

### ISSUE THREAD

**Issue by Rams25** [Hual/samp-discord-plugin#166]
Same plugin, free, and updated everyday.
You can use translate.google.com to translate the website.

Special thanks to Hual and french community.

**Comment by Rams25** [comment]
website available in english & french, go sampdiscord.fr

**Comment by AmyrAhmady** [comment]
Thanks and good luck, we appreciate that, Hual has been inactive for a while so he gave me permissions to do stuff here and maintain it, I will try my best to do daily update, people can choose what they want :)
