### ISSUE TITLE
DELUX MALLU ROLEPLAY

### ISSUE THREAD

**Issue by VloxL** [Hual/samp-discord-plugin#167]
![dmrp](https://user-images.githubusercontent.com/85962289/122107259-8f66fa80-ce23-11eb-80a9-69c25e6c68ab.jpg)

PLEASE MAKE ME THIS STATUS SERVER NAME ( DELUX MALLU ROLEPLAY ) 178.128.87.174:7777

**Comment by AmyrAhmady** [comment]
Server not available anymore, if you have new IP or you think we are wrong, please consider opening a **new issue**.
