### ISSUE TITLE
DELUX MALLU ROELPLAY SERVER IP : 139.99.61.130:7777

### ISSUE THREAD

**Issue by VloxL** [Hual/samp-discord-plugin#168]
![dmrp](https://user-images.githubusercontent.com/85962289/122108246-a65a1c80-ce24-11eb-9496-4aee30af9c53.jpg)

SERVER NAME ( DELUX MALLU ROLEPLAY ) SERVER IP : 139.99.61.130:7777

**Comment by AmyrAhmady** [comment]
Done
