### ISSUE TITLE
Le Monde Roleplay Issue with last add.

### ISSUE THREAD

**Issue by LaMoulaga** [Hual/samp-discord-plugin#173]
Hi, I want to apologize for making a request again, but the last picture I proposed to you and that you added and too dark so invisible on discord, we received mp from players who confirm it, I would like to put a new one if you agree.

Server IP : SERVEUR.LM-RP.FR:2600 and 213.32.83.152:2600

Server Name : Le Monde Roleplay

https://i.imgur.com/ArXmWJt.png

Thanks !

**Comment by AmyrAhmady** [comment]
Done
