### ISSUE TITLE
[GM] Guerras Mundiales [TDM]

### ISSUE THREAD

**Issue by SrManolo** [Hual/samp-discord-plugin#178]
IP: 198.100.154.62:7777      
Logo: 

<img width="960" alt="Guerras Mundiales" src="https://user-images.githubusercontent.com/87158025/125009724-796fe280-e03b-11eb-94de-3caee707beb9.png">

**Comment by AmyrAhmady** [comment]
Please read https://github.com/Hual/samp-discord-plugin#how-to-add-your-own-servers-with-custom-logos and make a proper logo that meets requirements then open a new issue.
