### ISSUE TITLE
[GvC] GTA Vietnam Community - Server Roleplay

### ISSUE THREAD

**Issue by JonHien** [Hual/samp-discord-plugin#179]
Hi Hual, Hope you read this from me soon.

Server Name: [GvC:RP] Project San Andreas Roleplay
IP Address: sv.gvc.vn:7777
IP Address Number: 45.124.84.33
Logo Server: https://i.imgur.com/KtQ5e9t.png

Youtube Server: https://www.youtube.com/c/onlyAbyss/videos

**Comment by JonHien** [comment]
@AmyrAhmady

**Comment by AmyrAhmady** [comment]
Your server is unavailable to access, and it seems to be offline, please create another issues if you think it's a mistake.
