### ISSUE TITLE
Red Roleplay

### ISSUE THREAD

**Issue by rookiegith** [Hual/samp-discord-plugin#180]
Hi Hual,

Server Name: Red Roleplay
IP: 92.222.217.3:7777
Logo: https://media.discordapp.net/attachments/863464666998505522/863908005317574656/logo.png?width=1200&height=469

Thank you for the plugin!

**Comment by AmyrAhmady** [comment]
Your server is unavailable to access, and it seems to be offline, please create another issues if you think it's a mistake.
