### ISSUE TITLE
San Andreas Global Roleplay

### ISSUE THREAD

**Issue by JawHoang** [Hual/samp-discord-plugin#182]
Hi Hual,

Server Name: [0.3-DL] San Andreas Global | SAGMP.VN
IP: 103.92.24.235:7777
Logo: https://i.im.ge/2021/07/23/73W1z.jpg

I from Vietnam, thank you very much for this plugin

**Comment by JawHoang** [comment]
@AmyrAhmady

**Comment by JawHoang** [comment]
@Hual

**Comment by AmyrAhmady** [comment]
Your server is unavailable to access, and it seems to be offline, please create another issues if you think it's a mistake.
