### ISSUE TITLE
Night Life Story

### ISSUE THREAD

**Issue by Aghyksa** [Hual/samp-discord-plugin#183]
IP : 202.6.239.14:7777

`https://discord.com/channels/835549033282928640/835549034386161671/861628832478134293`

Or
![pp](https://user-images.githubusercontent.com/58339173/126894716-48698f18-ad31-417c-a133-fffa1277fbf8.png)

**Comment by AmyrAhmady** [comment]
Please read https://github.com/Hual/samp-discord-plugin#how-to-add-your-own-servers-with-custom-logos
your logo does not meet the requirements 
create a new issue with proper logo next time if you still want your server to be added
