### ISSUE TITLE
Adel Roleplay

### ISSUE THREAD

**Issue by BrKcAn06** [Hual/samp-discord-plugin#189]
Server Name: Adel Roleplay
IP: 213.238.177.108:7777
Logo: https://www.adelroleplay.com/assets/img/logo.png

**Comment by AmyrAhmady** [comment]
Your server is unavailable to access, and it seems to be offline, please create another issues if you think it's a mistake.

**Comment by BrKcAn06** [comment]
Hi, we update to ip adress. New IP adress: 213.238.177.108:7777
