### ISSUE TITLE
GREAT INDONESIA Roleplay

### ISSUE THREAD

**Issue by yuuyrfavboy** [Hual/samp-discord-plugin#190]
IP:202.83.122.222
PORT:1111
![Pengurus SA-MP Great 20210816_215332](https://user-images.githubusercontent.com/69063045/129583868-10aee784-b8ac-4bce-876d-72304973f9fe.jpg)

**Comment by AmyrAhmady** [comment]
Your server is unavailable to access, and it seems to be offline, please create another issues if you think it's a mistake.
