### ISSUE TITLE
UnionGamers

### ISSUE THREAD

**Issue by Josephglz** [Hual/samp-discord-plugin#191]
**Name:** UnionGamers ~ Una Nueva Aventura
**IP:** 192.99.55.239
**Icon:** ![logo_ug](https://user-images.githubusercontent.com/29137137/130375903-6891270b-4f63-419d-8a60-9dcce3975dd9.jpg)

Thanks for the awesome plugin!

**Comment by AmyrAhmady** [comment]
Done
