### ISSUE TITLE
Night City Roleplay

### ISSUE THREAD

**Issue by gabrieltarife** [Hual/samp-discord-plugin#193]
![image](https://user-images.githubusercontent.com/89474690/130654269-4b6cc22e-004b-4b9a-9fa0-f26f70467f62.png)

IP: sv.night-city.fun:7777

**Comment by AmyrAhmady** [comment]
Please read https://github.com/Hual/samp-discord-plugin#how-to-add-your-own-servers-with-custom-logos
your logo does not meet the requirements
create a new issue with proper logo next time if you still want your server to be added
