### ISSUE TITLE
Gta Pinas Roleplay

### ISSUE THREAD

**Issue by Kymm05** [Hual/samp-discord-plugin#197]
![gtapinas-transparentdownsized](https://user-images.githubusercontent.com/86549126/132200494-2de74010-953c-4c16-a9ed-cd53c4c33a46.jpg)

139.162.22.156:7777

**Comment by AmyrAhmady** [comment]
Please read https://github.com/Hual/samp-discord-plugin#how-to-add-your-own-servers-with-custom-logos
your logo does not meet the requirements
create a new issue with proper logo next time if you still want your server to be added
