### ISSUE TITLE
Add server - Gamma.NoType.ro

### ISSUE THREAD

**Issue by peiN56** [Hual/samp-discord-plugin#20]
![untitled-2](https://user-images.githubusercontent.com/12189767/38812335-b6676e18-4194-11e8-9be1-05fa2a076b60.png)
Name: NoType Gamma RPG
IP: gamma.notype.ro

**Comment by Hual** [comment]
The minimum size for the logo is 512x512.

**Comment by peiN56** [comment]
![notypelogo2](https://user-images.githubusercontent.com/12189767/40614775-de32d7fc-628c-11e8-86b7-03d1cb937a01.png)
Done.
