### ISSUE TITLE
San Andreas Global Roleplay

### ISSUE THREAD

**Issue by JawHoang** [Hual/samp-discord-plugin#200]
Hi Hual,

Server Name: [0.3-DL] San Andreas Global | SAGMP.VN
IP: 103.98.152.57:7777
Logo: https://i.im.ge/2021/07/23/73W1z.jpg

Hello AmyrAhmady, i from Vietnam. I have blocked all international ip to avoid being hacked / ddoser and it only shows online in the region

**Comment by JawHoang** [comment]
![image](https://user-images.githubusercontent.com/87847424/132266397-3ef237c1-4d88-4259-8374-338e1f967b69.png)

**Comment by AmyrAhmady** [comment]
Done

**Comment by JawHoang** [comment]
Hello @AmyrAhmady, i was copy wrong ip :( i'm sorry you. this IP new: 103.98.152.57

**Comment by AmyrAhmady** [comment]
Okay, it's changed

**Comment by JawHoang** [comment]
Hello @AmyrAhmady, help me changed ip 51.79.251.47 . I was buy in ovh, sorry you!
