### ISSUE TITLE
New image for rich presence plugin

### ISSUE THREAD

**Issue by BlueFireRO** [Hual/samp-discord-plugin#204]
![4a78b8ed-7f6e-4e3b-8a19-a9bbdb60bf69-lanczos3](https://user-images.githubusercontent.com/64308848/133926948-41e1dfc2-35b2-4e36-b952-538adcdd7a0d.png)

ip: 
rpg.ultrakill.ro

**Comment by AmyrAhmady** [comment]
Your server is either offline or inaccessible, if you think this is a mistake, please open a new issue
