### ISSUE TITLE
New server image

### ISSUE THREAD

**Issue by ThiagoMCastro** [Hual/samp-discord-plugin#205]
![image](https://user-images.githubusercontent.com/48470238/133953288-e29877e6-e1b4-46db-b017-0b9d389bb68e.png)

IP: 142.44.255.127:7777

**Comment by NasiGorengTelur** [comment]
![SRPRP](https://user-images.githubusercontent.com/82102940/134755742-a48d05c4-0055-409e-bf03-607bcc6b89b7.png)

IP: 51.79.250.34:25564

**Comment by AmyrAhmady** [comment]
Your server is either offline or inaccessible, if you think this is a mistake, please open a new issue
