### ISSUE TITLE
Malabar City Role Play | Voice RP  [SA-MP]

### ISSUE THREAD

**Issue by Draco234** [Hual/samp-discord-plugin#206]
Malabar City Role Play | Voice RP 
IP : 91.121.87.14:7457
![rp](https://user-images.githubusercontent.com/74945227/135787958-f544816e-8759-45b9-985b-b180fa7442a0.png)

**Comment by Draco234** [comment]
Please Set This Server . I Already Did But That Host Got Down ITs A New Server . Please Do This Fast @AmyrAhmady

**Comment by Draco234** [comment]
@AmyrAhmady Please Can Anyone Close This Issue

**Comment by AmyrAhmady** [comment]
Your server is either offline or inaccessible, if you think this is a mistake, please open a new issue
