### ISSUE TITLE
App not closing after server quit.

### ISSUE THREAD

**Issue by HypeSzkodnik** [Hual/samp-discord-plugin#24]
GTA is not closing when quiting game, it freezes. Only thing to close the game is CTRL+ALT+DELETE and close gta_sa.exe process.
I tried:
- Put .asi file into root folder
- Put .asi file into folder in modloader
- Change asiloader/silent's asi loder.

My system info:
Windows 7 x64 SP 1

**Comment by Hual** [comment]
Resolved in 85bb34beb6961dc325c7f78e89d7f9596f6b1624.
