### ISSUE TITLE
add server

### ISSUE THREAD

**Issue by Autorojo** [Hual/samp-discord-plugin#25]
Can you add this server?

Name: Los Santos - Juego de Rol
IP: server.ls-rp.es:7777

![logo-lsrp-discord-richpresence](https://user-images.githubusercontent.com/33863751/40625226-90154a64-6287-11e8-821d-f62259cd198a.png)

Thank you!

**Comment by Autorojo** [comment]
Nevermind. This plugin is amazing, thanks for developing it!

**Comment by AGraber** [comment]
sorry this plugin is not for sale!
