### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by opysium** [Hual/samp-discord-plugin#29]
I install .asi to game folder but is not working.
You see Grand Theft Auto San Andreas
![screenshot_53](https://user-images.githubusercontent.com/40427422/41655483-af9d1892-7495-11e8-8d73-a8b0ef81e62d.png)

**Comment by opysium** [comment]
It happened after I updated Discord.

**Comment by ADoKaN** [comment]
Did you make sure to put it correctly with meeting the requirements of the specific ASI loader?
If you have CLEO, put it inside 'cleo' folder.
