### ISSUE TITLE
Server Logo Request (Medieval Roleplay)

### ISSUE THREAD

**Issue by DignitySAMP** [Hual/samp-discord-plugin#37]
Medieval Roleplay
51.68.126.166:7777
![icondiscord](https://user-images.githubusercontent.com/9262846/44620090-20454380-a88f-11e8-8451-c978a82bc989.png)

Thanks!

**Comment by BigETI** [comment]
that is going to haunt my nightmares

**Comment by DignitySAMP** [comment]
well, at least it's memorable :)
