### ISSUE TITLE
Client name don't update on discord when they are changed ingame

### ISSUE THREAD

**Issue by TommyB123** [Hual/samp-discord-plugin#4]
SA-MP names aren't updated properly when a server changes it after connecting. (e.g, SetPlayerName is used)

![example1](https://i.imgur.com/z2rqEaX.png)
![example2](https://i.imgur.com/Mske33W.png)

**Comment by Hual** [comment]
This can't really be solved because of the way the plugin works i.e. reads the arguments with which SA:MP was started.

**Comment by TommyB123** [comment]
lame as heck

**Comment by Hual** [comment]
delet

**Comment by AGraber** [comment]
hook the raknet client you lazy fuck

**Comment by Khanz** [comment]
why not @Hual

**Comment by Hual** [comment]
Because then it would become unstable and require more maintenance for no reason.
