### ISSUE TITLE
Coffee and SAMP

### ISSUE THREAD

**Issue by Kewlluminati** [Hual/samp-discord-plugin#41]
server.coffeeandsamp.com:7797

![images](https://user-images.githubusercontent.com/43355885/45650891-02ef4800-bad0-11e8-9c39-d7cd20f2cba3.png)

**Comment by BigETI** [comment]
![grafik](https://user-images.githubusercontent.com/4518424/45654043-58c8ed80-bada-11e8-83ac-6a704e6b28cd.png)

**Comment by GordoSatiro** [comment]
> 
> 
> ![grafik](https://user-images.githubusercontent.com/4518424/45654043-58c8ed80-bada-11e8-83ac-6a704e6b28cd.png)

![full-hd-6489081](https://user-images.githubusercontent.com/43631341/46316146-49977480-c59d-11e8-8972-505a60dde951.png)
