### ISSUE TITLE
Custom Logo Request 

### ISSUE THREAD

**Issue by MrKaish** [Hual/samp-discord-plugin#64]
City of Angels Roleplay
https://i.imgur.com/LobpQTs.png
51.77.200.63:7777

**Comment by BigETI** [comment]
> create an issue with a 512x512 logo attached and your server's IP address.

Your logo is 503x499. You can also upload your logo directly to GitHub:

![image](https://user-images.githubusercontent.com/4518424/64081018-89119800-ccfb-11e9-938d-3453f62584d1.png)

**Comment by MrKaish** [comment]
![coja](https://user-images.githubusercontent.com/33977453/64126007-5bd0f280-cdac-11e9-9c06-55b732169708.png)
here you go mate
