### ISSUE TITLE
it Adds my server Logo as `Pawno`'s Icon... (if Pawno window is launched behind gta_sa.exe)

### ISSUE THREAD

**Issue by Zorono** [Hual/samp-discord-plugin#70]

**Comment by Hual** [comment]
That's not true. It adds the icon if you're connecting to localhost.

**Comment by Zorono** [comment]
oh sorry, now i understand...
but please add an Programming Icon instead of Pawno...
similar to the attached one.
![programming](https://user-images.githubusercontent.com/19735243/69222472-39b46880-0b82-11ea-93ee-88d0695d92b0.png)

**Comment by Hual** [comment]
That's not the pawno logo, it's the pawn language logo so it's relevant.
