### ISSUE TITLE
create this one for me

### ISSUE THREAD

**Issue by asadkorii** [Hual/samp-discord-plugin#72]
![ec_rp](https://user-images.githubusercontent.com/57992652/70318214-579bf180-1841-11ea-8b9c-f79276d2e123.png)
and change San Andreas Multiplayer to Elite City Roleplay

I want to make it playing Elite City Roleplay, not San Andreas Roleplay.

**Comment by NERDZMAGNAT** [comment]
Change it from your app name on discord.com/developers and select your app :)
