### ISSUE TITLE
Server logo

### ISSUE THREAD

**Issue by AdamBryant95** [Hual/samp-discord-plugin#75]
Hello. 
Server name: Red County Roleplay - Hungary
IP Adress: 87.229.71.245:7777 or server.redcountyrp.hu
Logo (512X512):
![RCRP512](https://user-images.githubusercontent.com/44881205/72682603-06814d80-3acf-11ea-94c5-bfd7c10a69a1.png)

**Comment by AmyrAhmady** [comment]
Server is not available anymore.
