### ISSUE TITLE
Lux-Roleplay

### ISSUE THREAD

**Issue by atrophia** [Hual/samp-discord-plugin#78]
Hi there Hual, 

I'd like to add my server on the SAMP Discord Plugin, can this be possible anytime soon?
Btw since this is opensource, can you tell me how can I do this on my own? Because we might change IP-s and stuff and I want to have an on-go change without waiting for too long.
Thanks in advance, 
                    **_atrophia_**

HostName: [0.3-DL] LUX Roleplay | lux-roleplay.com
Address:  91.134.166.79:7778
Players:  X / 50
Ping:     32
Mode:     LUX:RP 1.7.9
Language: English

[Server Logo](https://cdn.discordapp.com/attachments/593889973078458377/594224465613815818/luxpng.png)

**Comment by Hual** [comment]
I have to add it manually. You can provide me with a domain name and update the IP it points to. Your logo doesn't meet the requirement.
