### ISSUE TITLE
add lsrp logo for plugin

### ISSUE THREAD

**Issue by Khanz** [Hual/samp-discord-plugin#8]
Here is the FoCo logo attached.

192.95.42.242:7777

![y3mpell](https://user-images.githubusercontent.com/4282736/36868763-46e3a808-1d91-11e8-981b-0beaa007f5de.png)

**Comment by Gigabitzz** [comment]
"FoCo" 🤔

**Comment by WisdomLS** [comment]
![logo](https://user-images.githubusercontent.com/37916915/38118414-80ec1f9e-33b2-11e8-8ef8-0b1319fe2704.png)

**Comment by WisdomLS** [comment]
New IP now

server.ls-rp.io:7777
