### ISSUE TITLE
Custom logo request

### ISSUE THREAD

**Issue by Chaprnks** [Hual/samp-discord-plugin#81]
IP: server.gta.sh:7777

Logo:
![discord-rpc](https://user-images.githubusercontent.com/6340970/78463643-57a3e500-76ad-11ea-8485-f164f9e9bcd4.png)

**Comment by ManojWarWay** [comment]
Server Name  : Bzone
IP : rpg.b-zone.ro:7777

The Logo
![bzone logo](https://user-images.githubusercontent.com/42494649/78886628-2d22a500-7a7c-11ea-806b-9026a84f4da0.png)
