### ISSUE TITLE
Requesting server logo

### ISSUE THREAD

**Issue by Greek45** [Hual/samp-discord-plugin#97]
play.uifserver.net:7776 or 51.254.85.134:7776

![phpL7f2y3_c2PM](https://user-images.githubusercontent.com/63285146/85061957-9f75cc80-b132-11ea-907b-f414752b60e3.jpg)

**Comment by Hual** [comment]
Image doesn't meet the minimum size requirement

**Comment by Greek45** [comment]
Hi, I resized the image to 512x512. Is everything fine right now? here's
the image  https://imgur.com/yhkhziE

**Comment by Greek45** [comment]
> Image doesn't meet the minimum size requirement

Hi, I resized the image to 512x512. Is everything fine right now? here's
the image 
![hqdefault](https://user-images.githubusercontent.com/63285146/85072235-659fd700-b1c1-11ea-8471-afb27396b0aa.png)

**Comment by Greek45** [comment]
Hi man, 1 last question because i'm facing an unknown problem. Can you tell
me how to install it? is it just 1 file or what? Sorry for the spam

**Comment by Hual** [comment]
Use an ASI loader
