### ISSUE TITLE
SampDroid RP 512x512

### ISSUE THREAD

**Issue by GalaxyGames2018** [Hual/samp-discord-plugin#98]
![logo-sampdroid-rich](https://user-images.githubusercontent.com/50090767/85171259-48f0b700-b234-11ea-8c0f-f60f9a201284.png)
IP: 51.79.69.122:7777

**Comment by Hual** [comment]
I don't support theft of SAMP code.

**Comment by AmyrAhmady** [comment]
needs samp optimizer
