### ISSUE TITLE
Swat vs Terrorists - TDM

### ISSUE THREAD

**Issue by AvySv12** [Hual/samp-discord-plugin#99]
IP: 91.134.166.78:7777
Logo: 
https://images-ext-2.discordapp.net/external/_QF3RqO6llWxQ4BOM_2Bbiburr5Vl6CGYWllYzT6RxQ/https/i.imgur.com/I777VfH.mp4

**Comment by BigETI** [comment]
An MP4 as logo, how does that work?

**Comment by AvySv12** [comment]
Okay use this: https://media.discordapp.net/attachments/723964928503054359/725033400791990352/avtDiscord2.png

**Comment by BigETI** [comment]
> If you'd like your server added to the custom logos list, create an issue with a 512x512 logo attached and your server's IP address.

> [...] **512x512 logo** [...]

**Comment by AvySv12** [comment]
512x512 logo: https://media.discordapp.net/attachments/724646520380719166/725381545073967675/20200624_081521.png?width=475&height=475
